
CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL NOT NULL,
  "userauthid" UUID UNIQUE NOT NULL,
  "firstname" VARCHAR(255) NULL,
  "lastname" VARCHAR(255) NULL,
  "username" VARCHAR(255) UNIQUE NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "phone" VARCHAR(255) NULL,
  "profilepic" VARCHAR(255) NULL,
  "recordstatus" SMALLINT DEFAULT 0 NOT NULL,
  "isverifiedemail" BOOLEAN DEFAULT FALSE NOT NULL,
  "isverifiedphone" BOOLEAN DEFAULT FALSE NOT NULL,
  "createdat" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedat" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);
