
CREATE TABLE IF NOT EXISTS "clientusers" (
  "id" SERIAL NOT NULL,
  "userid" INTEGER NOT NULL REFERENCES users (id),
  "clientid" INTEGER NOT NULL REFERENCES clients (id),
  "recordstatus" SMALLINT DEFAULT 0 NOT NULL,
  "createdat" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedat" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("userid","clientid")
);
