
CREATE TABLE IF NOT EXISTS "articletags" (
  "id" SERIAL NOT NULL,
  "articleid" INTEGER NOT NULL REFERENCES articles (id),
  "tagid" INTEGER NOT NULL REFERENCES tags (id),
  "recordstatus" SMALLINT DEFAULT 0 NOT NULL,
  "createdat" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedat" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("articleid","tagid")
);
