DROP TABLE IF EXISTS "clients";

DROP TABLE IF EXISTS "users";

DROP TABLE IF EXISTS "clientusers";

DROP TABLE IF EXISTS "genres";

DROP TABLE IF EXISTS "tags";

DROP TABLE IF EXISTS "articles";

DROP TABLE IF EXISTS "articletags";
